<?php

namespace Minioak\Royalmail\Shipping;

/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'identificationStructure' => '\\Minioak\\Royalmail\\Shipping\\Structs\\IdentificationStructure',
            'integrationHeader' => '\\Minioak\\Royalmail\\Shipping\\Structs\\IntegrationHeader',
            'errorDetail' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ErrorDetail',
            'errorStructure' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ErrorStructure',
            'warningDetail' => '\\Minioak\\Royalmail\\Shipping\\Structs\\WarningDetail',
            'warningStructure' => '\\Minioak\\Royalmail\\Shipping\\Structs\\WarningStructure',
            'integrationFooter' => '\\Minioak\\Royalmail\\Shipping\\Structs\\IntegrationFooter',
            'businessFunctionType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\BusinessFunctionType',
            'addressUsageType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\AddressUsageType',
            'bFPOFormatType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\BFPOFormatType',
            'calendarType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CalendarType',
            'contactMethodType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ContactMethodType',
            'contactUsageType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ContactUsageType',
            'countryType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CountryType',
            'countyType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CountyType',
            'currencyType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CurrencyType',
            'dateFormatType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DateFormatType',
            'dayOfWeekType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DayOfWeekType',
            'durationType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DurationType',
            'functionalLocationRelationshipType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\FunctionalLocationRelationshipType',
            'functionalLocationSubType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\FunctionalLocationSubType',
            'functionalLocationType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\FunctionalLocationType',
            'geospatialPositionType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\GeospatialPositionType',
            'mailClassType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\MailClassType',
            'mailItemFormatType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\MailItemFormatType',
            'nameSuffixType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\NameSuffixType',
            'nameType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\NameType',
            'nonWorkingDayType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\NonWorkingDayType',
            'postageSizeType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PostageSizeType',
            'referenceDataType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ReferenceDataType',
            'roleType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\RoleType',
            'serviceEnhancementType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceEnhancementType',
            'serviceFormatType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceFormatType',
            'serviceOfferingType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceOfferingType',
            'stateOrProvinceType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\StateOrProvinceType',
            'statusType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\StatusType',
            'systemNameType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SystemNameType',
            'taxType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TaxType',
            'titleType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TitleType',
            'unitOfMeasureType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\UnitOfMeasureType',
            'workingDayType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\WorkingDayType',
            'functionalLocationGroupType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\FunctionalLocationGroupType',
            'postcode' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Postcode',
            'formatDatetime' => '\\Minioak\\Royalmail\\Shipping\\Structs\\FormatDatetime',
            'address' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Address',
            'amount' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Amount',
            'audit' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Audit',
            'contactMechanism' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ContactMechanism',
            'digitalAddress' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DigitalAddress',
            'dimension' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Dimension',
            'geoSpatialPosition' => '\\Minioak\\Royalmail\\Shipping\\Structs\\GeoSpatialPosition',
            'status' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Status',
            'systemCrossReference' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SystemCrossReference',
            'telephoneNumber' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TelephoneNumber',
            'detail' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Detail',
            'exceptionDetails' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ExceptionDetails',
            'baseRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\BaseRequest',
            'createShipmentRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CreateShipmentRequest',
            'createShipmentResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CreateShipmentResponse',
            'requestedShipment' => '\\Minioak\\Royalmail\\Shipping\\Structs\\RequestedShipment',
            'internationalInfo' => '\\Minioak\\Royalmail\\Shipping\\Structs\\InternationalInfo',
            'parcels' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Parcels',
            'parcel' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Parcel',
            'contentDetails' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ContentDetails',
            'contentDetail' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ContentDetail',
            'contact' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Contact',
            'serviceEnhancements' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceEnhancements',
            'items' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Items',
            'item' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Item',
            'shipment' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Shipment',
            'completedShipmentInfo' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedShipmentInfo',
            'allCompletedShipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\AllCompletedShipments',
            'completedShipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedShipments',
            'shipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Shipments',
            'printLabelRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintLabelRequest',
            'localisedAddress' => '\\Minioak\\Royalmail\\Shipping\\Structs\\LocalisedAddress',
            'printLabelResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintLabelResponse',
            'labelImages' => '\\Minioak\\Royalmail\\Shipping\\Structs\\LabelImages',
            'labelData' => '\\Minioak\\Royalmail\\Shipping\\Structs\\LabelData',
            'createManifestRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CreateManifestRequest',
            'createManifestResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CreateManifestResponse',
            'completedManifests' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedManifests',
            'completedManifestInfo' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedManifestInfo',
            'manifestShipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ManifestShipments',
            'manifestShipment' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ManifestShipment',
            'printManifestRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintManifestRequest',
            'printManifestResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintManifestResponse',
            'updateShipmentRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\UpdateShipmentRequest',
            'updateShipmentResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\UpdateShipmentResponse',
            'cancelShipmentRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CancelShipmentRequest',
            'cancelShipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CancelShipments',
            'cancelShipmentResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CancelShipmentResponse',
            'completedCancelInfo' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedCancelInfo',
            'completedCancelShipments' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CompletedCancelShipments',
            'printDocumentRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintDocumentRequest',
            'printDocumentResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PrintDocumentResponse',
            'request1DRangesRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Request1DRangesRequest',
            'serviceReferences' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceReferences',
            'serviceReference' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceReference',
            'request1DRangesResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Request1DRangesResponse',
            'serviceRanges' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceRanges',
            'serviceRange' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ServiceRange',
            'barcode1DRange' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Barcode1DRange',
            'request2DItemIDRangeRequest' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Request2DItemIDRangeRequest',
            'request2DItemIDRangeResponse' => '\\Minioak\\Royalmail\\Shipping\\Structs\\Request2DItemIDRangeResponse',
            'itemIDRange' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ItemIDRange',
            'AttributedDateTime' => '\\Minioak\\Royalmail\\Shipping\\Structs\\AttributedDateTime',
            'AttributedURI' => '\\Minioak\\Royalmail\\Shipping\\Structs\\AttributedURI',
            'TimestampType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TimestampType',
            'SignatureType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignatureType',
            'SignatureValueType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignatureValueType',
            'SignedInfoType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignedInfoType',
            'CanonicalizationMethodType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\CanonicalizationMethodType',
            'SignatureMethodType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignatureMethodType',
            'ReferenceType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ReferenceType',
            'TransformsType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TransformsType',
            'TransformType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TransformType',
            'DigestMethodType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DigestMethodType',
            'KeyInfoType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\KeyInfoType',
            'KeyValueType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\KeyValueType',
            'RetrievalMethodType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\RetrievalMethodType',
            'X509DataType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\X509DataType',
            'X509IssuerSerialType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\X509IssuerSerialType',
            'PGPDataType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PGPDataType',
            'SPKIDataType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SPKIDataType',
            'ObjectType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ObjectType',
            'ManifestType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\ManifestType',
            'SignaturePropertiesType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignaturePropertiesType',
            'SignaturePropertyType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SignaturePropertyType',
            'DSAKeyValueType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\DSAKeyValueType',
            'RSAKeyValueType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\RSAKeyValueType',
            'AttributedString' => '\\Minioak\\Royalmail\\Shipping\\Structs\\AttributedString',
            'PasswordString' => '\\Minioak\\Royalmail\\Shipping\\Structs\\PasswordString',
            'EncodedString' => '\\Minioak\\Royalmail\\Shipping\\Structs\\EncodedString',
            'UsernameTokenType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\UsernameTokenType',
            'BinarySecurityTokenType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\BinarySecurityTokenType',
            'KeyIdentifierType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\KeyIdentifierType',
            'EmbeddedType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\EmbeddedType',
            'SecurityTokenReferenceType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SecurityTokenReferenceType',
            'SecurityHeaderType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\SecurityHeaderType',
            'TransformationParametersType' => '\\Minioak\\Royalmail\\Shipping\\Structs\\TransformationParametersType',
        );
    }
}
